-- Database bootstrap for Made in Hainaut staging environment
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  client_submitted_at TIMESTAMPTZ,
  raison_sociale TEXT NOT NULL,
  adresse TEXT NOT NULL,
  code_postal TEXT NOT NULL,
  ville TEXT NOT NULL,
  pays TEXT NOT NULL,
  tel TEXT NOT NULL,
  site_internet TEXT,
  siret TEXT,
  tva_intra TEXT,
  membre_association BOOLEAN NOT NULL,
  exposant_2024 BOOLEAN NOT NULL,
  activite_industrie BOOLEAN NOT NULL,
  activite_transport_logistique BOOLEAN NOT NULL,
  activite_btp_construction_logement BOOLEAN NOT NULL,
  activite_environnement_energie BOOLEAN NOT NULL,
  activite_services_entreprises BOOLEAN NOT NULL,
  activite_image_nouvelles_technologies BOOLEAN NOT NULL,
  activite_tourisme_bien_etre BOOLEAN NOT NULL,
  activite_autre BOOLEAN NOT NULL,
  autre_activite TEXT,
  facturation_adresse TEXT,
  facturation_cp TEXT,
  facturation_ville TEXT,
  facturation_pays TEXT,
  contact_compta_nom TEXT,
  contact_compta_tel TEXT,
  contact_compta_mail TEXT,
  responsable_nom TEXT,
  responsable_prenom TEXT,
  responsable_tel TEXT,
  responsable_mail TEXT,
  resp_op_nom TEXT,
  resp_op_prenom TEXT,
  resp_op_tel TEXT,
  resp_op_mail TEXT,
  enseigne TEXT,
  stand_type TEXT,
  stand_size TEXT,
  stand_angles INTEGER,
  electricity_upgrade TEXT,
  exterior_space BOOLEAN NOT NULL,
  exterior_surface TEXT,
  garden_cottage BOOLEAN NOT NULL,
  micro_stand BOOLEAN NOT NULL,
  reserve_porte_melamine INTEGER NOT NULL,
  moquette_differente INTEGER NOT NULL,
  moquette_couleur TEXT,
  velum_stand INTEGER NOT NULL,
  cloison_bois_gainee INTEGER NOT NULL,
  reserve_porte_bois INTEGER NOT NULL,
  bandeau_signaletique INTEGER NOT NULL,
  comptoir INTEGER NOT NULL,
  tabouret INTEGER NOT NULL,
  mange_debout INTEGER NOT NULL,
  chaise INTEGER NOT NULL,
  table_120x60 INTEGER NOT NULL,
  mange_3_tabourets INTEGER NOT NULL,
  ecran_52 INTEGER NOT NULL,
  refrigerateur_140 INTEGER NOT NULL,
  refrigerateur_240 INTEGER NOT NULL,
  presentoir_a4 INTEGER NOT NULL,
  bloc_prises INTEGER NOT NULL,
  fauteuil INTEGER NOT NULL,
  table_basse INTEGER NOT NULL,
  gueridon_haut INTEGER NOT NULL,
  pouf_cube INTEGER NOT NULL,
  pouf_couleur TEXT,
  colonne_vitrine INTEGER NOT NULL,
  comptoir_vitrine INTEGER NOT NULL,
  porte_manteaux INTEGER NOT NULL,
  plante_bambou INTEGER NOT NULL,
  plante_kentia INTEGER NOT NULL,
  scan_badges BOOLEAN NOT NULL,
  pass_soiree INTEGER NOT NULL,
  pack_signaletique_complet BOOLEAN NOT NULL,
  signaletique_comptoir BOOLEAN NOT NULL,
  signaletique_haut_cloisons BOOLEAN NOT NULL,
  signaletique_cloisons_lineaires INTEGER NOT NULL,
  signaletique_enseigne_haute BOOLEAN NOT NULL,
  demi_page_catalogue BOOLEAN NOT NULL,
  page_complete_catalogue BOOLEAN NOT NULL,
  deuxieme_couverture BOOLEAN NOT NULL,
  quatrieme_couverture BOOLEAN NOT NULL,
  logo_plan_salon BOOLEAN NOT NULL,
  documentation_sac_visiteur BOOLEAN NOT NULL,
  distribution_hotesse BOOLEAN NOT NULL,
  mode_reglement TEXT NOT NULL,
  accepte_reglement BOOLEAN NOT NULL,
  date_signature DATE,
  cachet_signature TEXT,
  total_ht_section1 NUMERIC(12,2) NOT NULL,
  total_ht_section2 NUMERIC(12,2) NOT NULL,
  total_ht_section3 NUMERIC(12,2) NOT NULL,
  total_ht NUMERIC(12,2) NOT NULL,
  total_tva NUMERIC(12,2) NOT NULL,
  total_ttc NUMERIC(12,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_submissions_submitted_at ON submissions (submitted_at);

CREATE TABLE IF NOT EXISTS co_exposants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id UUID NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  nom_entreprise TEXT NOT NULL,
  nom_responsable TEXT,
  prenom_responsable TEXT,
  tel_responsable TEXT,
  mail_responsable TEXT
);

CREATE INDEX IF NOT EXISTS idx_co_exposants_submission ON co_exposants (submission_id);
